# pseudo inverse matrix 

In this example, we calculate pseudo inverse matrix with SVD (manually).

Pseudo inverse matrix of  $X = U \Sigma V^T$  is  

$X^+=V\Sigma^+ U^T$

$\Sigma^+$ is formed by taking the reciprocal of all the non-zero elements from $\Sigma$, leaving all the zeros alone, making the matrix the right shape.

In [1]:
import sys
import sklearn
import numpy as np
import os
# to make this notebook's output stable across runs
np.random.seed(42)

generate 3D dataset (10 x 3dim) 


In [2]:
m = 10
w1, w2 = 0.1, 0.3
noise = 0.1

angles = np.random.rand(m) * 3 * np.pi / 2 - 0.5
X = np.empty((m, 3))
X[:, 0] = np.cos(angles) + np.sin(angles)/2 + noise * np.random.randn(m) / 2
X[:, 1] = np.sin(angles) * 0.7 + noise * np.random.randn(m) / 2
X[:, 2] = X[:, 0] * w1 + X[:, 1] * w2 + noise * np.random.randn(m)

In [3]:
print(X.shape)
print(f' X is : \n {X}')

(10, 3)
 X is : 
 [[ 0.75439978  0.62211958  0.20201198]
 [-1.01325399 -0.59118406 -0.30784999]
 [-0.90928024  0.20696297 -0.08900979]
 [-0.33941898  0.50074292  0.3015088 ]
 [ 1.1010898   0.16651662  0.15871424]
 [ 0.9932989   0.09182542  0.02110642]
 [ 0.7760796  -0.18427194  0.10458087]
 [-1.14584015 -0.2927168  -0.32448342]
 [-0.37916691  0.44892249  0.11764642]
 [-0.78808185  0.22890949 -0.20610235]]


### perform SVD

In [4]:
# Perform SVD
U, s, Vt = np.linalg.svd(X)

print(f' shape of U = {U.shape}')
print(f' shape of s = {s.shape}')
print(f' shape of Vt = {Vt.shape}')

# create a cov matrix S from s
m, n = X.shape
S = np.zeros(X.shape)
S[:n, :n] = np.diag(s)

print(f' shape of S = {S.shape}')

 shape of U = (10, 10)
 shape of s = (3,)
 shape of Vt = (3, 3)
 shape of S = (10, 3)


confirm the reconstruction

In [5]:
# confirm reconstruction
X_reconst = U.dot(S).dot(Vt)
print(f' reconstruction of X is :\n {X_reconst}')

 reconstruction of X is :
 [[ 0.75439978  0.62211958  0.20201198]
 [-1.01325399 -0.59118406 -0.30784999]
 [-0.90928024  0.20696297 -0.08900979]
 [-0.33941898  0.50074292  0.3015088 ]
 [ 1.1010898   0.16651662  0.15871424]
 [ 0.9932989   0.09182542  0.02110642]
 [ 0.7760796  -0.18427194  0.10458087]
 [-1.14584015 -0.2927168  -0.32448342]
 [-0.37916691  0.44892249  0.11764642]
 [-0.78808185  0.22890949 -0.20610235]]


In [6]:
# confirm it is identical to the original
# if true, they are element-wise equal within a tolerance (1e-8+ 1e-5 * n).
np.allclose(X, X_reconst)

True

calculation of pseudo inverse matrix  

First, we calculate $\Sigma^+$ from $\Sigma$.

In [7]:
# calculation of pseudo-inverse-matrix X+
S_tmp = np.reciprocal(S, where=S!=0) # calculate reciprocal except 0
S_Pinv = S_tmp.T

In [8]:
print(S)

[[2.78406863 0.         0.        ]
 [0.         1.20091856 0.        ]
 [0.         0.         0.31002664]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]


In [9]:
print(S_Pinv)

[[3.59186548e-01 4.44089210e-16 1.11022302e-16 5.55111512e-17
  2.22044605e-16 1.11022302e-16 3.33066907e-16 2.22044605e-16
  5.55111512e-17 3.33066907e-16]
 [2.22044605e-16 8.32695931e-01 2.22044605e-16 2.22044605e-16
  2.77555756e-17 6.93889390e-17 3.33066907e-16 5.55111512e-17
  3.33066907e-16 2.22044605e-16]
 [8.32667268e-17 1.66533454e-16 3.22552927e+00 5.55111512e-17
  0.00000000e+00 4.51028104e-17 6.93889390e-17 5.55111512e-17
  4.16333634e-17 5.55111512e-17]]


Pseudo inverse matrix of $X$ is 

$X^+ = V \Sigma^+ U^T$ 

In [10]:
# calculation of pseudo inverse
X_Pinv = (Vt.T).dot(S_Pinv).dot(U.T)

In [11]:
print(f'size of X      = {X.shape}')
print(f'size of X_Pinv = {X_Pinv.shape}')

size of X      = (10, 3)
size of X_Pinv = (3, 10)


In [12]:
print(X_Pinv)

[[ 0.16111931 -0.1027007  -0.10532153 -0.31899551  0.18595017  0.29723384
   0.05344387 -0.03688248 -0.12547462  0.07734477]
 [ 0.64783355 -0.36834913  0.33108089 -0.1476345   0.13089358  0.37304553
  -0.37696618  0.1263186   0.28371517  0.73700536]
 [-0.8070458   0.04375969 -0.33219534  1.77650925 -0.31938702 -1.25645366
   0.57156168 -0.80756049  0.26207929 -1.62960761]]


### Now confirm pseudo inverse matrix works

(1) $X^+ X$  
Looks it works.

In [13]:
# confirm X X_Pinv
# this works
pseudoI = X_Pinv.dot(X)
print(pseudoI)

[[ 1.00000000e+00  5.18245460e-16  1.51992149e-16]
 [ 1.11794141e-15  1.00000000e+00  2.51706480e-16]
 [-3.24009831e-16  5.70561997e-17  1.00000000e+00]]


(2) $XX^+$  
Looks it does not work.  
The calculation of pseudo-inverse matrices in higher order dimensions is generally not accurate due to ill-conditioning.


In [14]:
# confirm X X_Pinv (2)
# this does not work
pseudoI_2 = X.dot(X_Pinv)
print(pseudoI_2)

[[ 0.36154538 -0.29779461  0.05940993  0.0263797   0.15719222  0.20249337
  -0.07873769 -0.11237576  0.13478989  0.18765408]
 [-0.29779461  0.3083526   0.01325404 -0.13639572 -0.16747366 -0.13491269
  -0.00725108  0.21130127 -0.12127133 -0.01240103]
 [ 0.05940993  0.01325404  0.19385691  0.10137472 -0.11356212 -0.08122557
  -0.17748808  0.13156058  0.14948251  0.22725578]
 [ 0.0263797  -0.13639572  0.10137472  0.56997937 -0.09386898 -0.29291873
  -0.03457213 -0.16771483  0.26367604 -0.1485431 ]
 [ 0.15719222 -0.16747366 -0.11356212 -0.09386898  0.17585252  0.18998234
   0.08679035 -0.14774813 -0.04931982 -0.05075476]
 [ 0.20249337 -0.13491269 -0.08122557 -0.29291873  0.18998234  0.30297787
   0.03053428 -0.04208078 -0.09304998  0.11010712]
 [-0.07873769 -0.00725108 -0.17748808 -0.03457213  0.08679035  0.03053428
   0.17071541 -0.13635609 -0.12225056 -0.24620949]
 [-0.11237576  0.21130127  0.13156058 -0.16771483 -0.14774813 -0.04208078
  -0.13635609  0.26732584 -0.02431472  0.22442205]


Calculation of pseudo inverse matrix with numpy function.

In [15]:
from numpy.linalg import pinv 

X_Pinv2 = pinv(X)
print(X_Pinv2)

[[ 0.16111931 -0.1027007  -0.10532153 -0.31899551  0.18595017  0.29723384
   0.05344387 -0.03688248 -0.12547462  0.07734477]
 [ 0.64783355 -0.36834913  0.33108089 -0.1476345   0.13089358  0.37304553
  -0.37696618  0.1263186   0.28371517  0.73700536]
 [-0.8070458   0.04375969 -0.33219534  1.77650925 -0.31938702 -1.25645366
   0.57156168 -0.80756049  0.26207929 -1.62960761]]


In [16]:
print(X_Pinv2.dot(X))

[[ 1.00000000e+00  4.84066735e-17  4.05464113e-17]
 [ 7.20907483e-16  1.00000000e+00  2.05942566e-16]
 [-4.98999153e-16  2.18906620e-16  1.00000000e+00]]


In [17]:
print(X.dot(X_Pinv2))

[[ 0.36154538 -0.29779461  0.05940993  0.0263797   0.15719222  0.20249337
  -0.07873769 -0.11237576  0.13478989  0.18765408]
 [-0.29779461  0.3083526   0.01325404 -0.13639572 -0.16747366 -0.13491269
  -0.00725108  0.21130127 -0.12127133 -0.01240103]
 [ 0.05940993  0.01325404  0.19385691  0.10137472 -0.11356212 -0.08122557
  -0.17748808  0.13156058  0.14948251  0.22725578]
 [ 0.0263797  -0.13639572  0.10137472  0.56997937 -0.09386898 -0.29291873
  -0.03457213 -0.16771483  0.26367604 -0.1485431 ]
 [ 0.15719222 -0.16747366 -0.11356212 -0.09386898  0.17585252  0.18998234
   0.08679035 -0.14774813 -0.04931982 -0.05075476]
 [ 0.20249337 -0.13491269 -0.08122557 -0.29291873  0.18998234  0.30297787
   0.03053428 -0.04208078 -0.09304998  0.11010712]
 [-0.07873769 -0.00725108 -0.17748808 -0.03457213  0.08679035  0.03053428
   0.17071541 -0.13635609 -0.12225056 -0.24620949]
 [-0.11237576  0.21130127  0.13156058 -0.16771483 -0.14774813 -0.04208078
  -0.13635609  0.26732584 -0.02431472  0.22442205]
